version: '3'

services:
  db:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

  rembg:
    image: danielgatis/rembg:latest
    restart: unless-stopped
    command: ["s"]
    ports:
      - 7000:7000

volumes:
  mongodata:
